apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubemcp.serviceAccountName" . }}
  labels:
    {{- include "kubemcp.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubemcp.serviceAccountName" . }}
  labels:
    {{- include "kubemcp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubemcp.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubemcp.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
